### PR TITLE
Root Owned File Fix

### LINKED ISSUE #18: Files owned by root can't be found in LDAP and stop Sandman
Files owned by root have an ID of `0` which sandman won't find in the LDAP records, so it'll stop. Although stopping immediately if something goes wrong is what we want, this case should be dealt with individually (i.e. skipping the files)

### PR DESCRIPTION
**Pull request by michael-grace**
Might as well actually open this as a PR as these are now what we're doing (even if I did code this in November then we all got distracted).

Fixes: #18 

- Files owned by the root user can't be actioned by Sandman - this should fail when the file is found, not when it tries to send an email to them
- Also introduces a MockMailer class if you want to test sending emails

As this was coded so long ago, there are conflicts. I'll sort those :)

### CODE REVIEW

**Review by sb10 — CHANGES_REQUESTED** [review]
Looks good to me. Can you add tests to cover the lines that Codecov complains about?

It would be especially good to see an example of using your mock_mailer via a test that uses it.

**Comment by sb10** [comment]
[As an admin, I want sandman to fail early on root-owned files, so that it doesn't waste time and try to email root](https://trello.com/c/bld6pLoH/17-as-an-admin-i-want-sandman-to-fail-early-on-root-owned-files-so-that-it-doesnt-waste-time-and-try-to-email-root)

**Comment by sb10** [comment]
[Fix root-owned files](https://trello.com/c/8JkJkSXW/40-fix-root-owned-files)

**Comment by michael-grace** [comment]
Well, that was an absolute mess of rebasing. But it's done.

I've left it as three commits, because it's three separate things that I don't think should be squashed together when merged to develop.
- The Unactionable File Code and tests
- The mock mailer class and tests
- A bug fix

**Review by sb10 — DISMISSED** [review]
Thanks!

**Review by sb10 — APPROVED** [review]

**Pull request merged**
