### PR TITLE
Test with the same python we use in production.

### PR DESCRIPTION
**Pull request by sb10**

### CODE REVIEW

**Comment by michael-grace** [comment]
Yeah, this is good. Could the commits match the commit template? https://github.com/wtsi-hgi/hgi-vault/blob/develop/doc/dev/design.md#commit-message-template

**Comment by sb10** [comment]
> Yeah, this is good. Could the commits match the commit template? https://github.com/wtsi-hgi/hgi-vault/blob/develop/doc/dev/design.md#commit-message-template

Yes, I'll write them that way during the squash, and use the template in future.

**Review by michael-grace — DISMISSED** [review]

**Review by michael-grace — APPROVED** [review]

**Comment by sb10** [comment]
[As an admin, I want travis CI to be testing with the same version of python as we use in production, so that CI better reflects what we might see](https://trello.com/c/ouCVU1RF/16-as-an-admin-i-want-travis-ci-to-be-testing-with-the-same-version-of-python-as-we-use-in-production-so-that-ci-better-reflects-wh)

**Comment by sb10** [comment]
[Change travis CI config to tests with python 3.9](https://trello.com/c/ylh3cBHr/38-change-travis-ci-config-to-tests-with-python-39)

**Pull request merged**
