### PR TITLE
Fix formatting with autopep8

### PR DESCRIPTION
**Pull request by sb10**
There isn't anything in the codebase to force or check that future files conform to pep8. Any ideas on how to do that?

### CODE REVIEW

**Review by piyushahuja — DISMISSED** [review]

**Comment by sb10** [comment]
Have installed pep8speaks on the repo, though it is saying something that doesn't make much sense. Manually running:

```
pycodestyle --max-line-length 160 .
```

Shows no issues, but pep8speaks thinks there's still an issue with api/idm/idm.py. Ignoring this.

**Review by michael-grace — COMMENTED** [review]
- not sure about the E251 errors - shouldn't really happen, but it is how it is.

- 160 characters is quite long, as it'll just be strings, i think we should look at manually reformatting them, so we can get it down to ~80 character max, i.e. we can do this is python

```python
>>> def a ():
...     # note the lack of comma after "abc"
...     print(("abc" 
...             "def"))
...
>>> a()
abcdef
```

**Comment by sb10** [comment]
> * 160 characters is quite long, as it'll just be strings, i think we should look at manually reformatting them, so we can get it down to ~80 character max

I manually fixed the few lines that were longer than 160, but there were too many lines between 80 and 160 to deal with:

```
$ pycodestyle . | wc -l
181
```

It's not intractable, but do you think it's worth spending the time on?

**Comment by sb10** [comment]
(and for whatever reason, `autopep8` doesn't want to fix these long lines)

**Comment by sb10** [comment]
The main aim here is to allow new code to be written with automated autopep8 formatting turned on, without that resulting in format changes in the diff. Since autopep8 doesn't touch the existing lines longer than 79 chars, I think it's fine to leave them.

**Comment by michael-grace** [comment]
yeah, that's valid

**Review by michael-grace — APPROVED** [review]

**Comment by sb10** [comment]
[Run `autopep8 -ir .`](https://trello.com/c/0TA0o2ZW/37-run-autopep8-ir)

**Pull request merged**
